app.py
import os

from flask import Flask, render_template

from views.simplearmory import simplearmory_blueprint
from views.spec_ratings import spec_ratings_blueprint

app = Flask(__name__)
app.secret_key = os.environ.get('SECRET_KEY')
app.config.update(
    ADMIN=os.environ.get('ADMIN')
)

app.register_blueprint(spec_ratings_blueprint, url_prefix='/spec-ratings')
app.register_blueprint(simplearmory_blueprint, url_prefix='/simplearmory')


@app.route('/')
def index():
    return render_template('index.html')


if __name__ == '__main__':
    app.run()

views/simplearmory.py
from flask import Blueprint, render_template

simplearmory_blueprint = Blueprint('simeplearmory', __name__)


@simplearmory_blueprint.route('/', methods=['GET'])
def index():
    return render_template('simplearmory/mounts.html')

views/spec_ratings.py
import json
from json import JSONDecodeError

from flask import Blueprint, render_template, request, flash, session

spec_ratings_blueprint = Blueprint('spec_ratings', __name__)

wow_classes = [
    ('deathknight', 'blood,frost,unholy'),
    ('demonhunter', 'havoc,vengence'),
    ('druid', 'balance,feral,guardian,restoration'),
    ('hunter', 'beastmastery,marksmanship,survival'),
    ('mage', 'arcane,fire,frost'),
    ('monk', 'brewmaster,mistweaver,windwalker'),
    ('paladin', 'holy,protection,retribution'),
    ('priest', 'discipline,holy,shadow'),
    ('rogue', 'assassination,outlaw,subtlety'),
    ('shaman', 'elemental,enhancement,restoration'),
    ('warlock', 'affliction,demonology,destruction'),
    ('warrior', 'arms,fury,protection')
]


@spec_ratings_blueprint.route('/', methods=['GET'])
def index():
    return render_template('ratings/spec_ratings.html')


@spec_ratings_blueprint.route('/load-ratings', methods=['GET', 'POST'])
def load_ratings():
    if request.method == 'POST':
        ratings_json = request.form.get('spec-ratings')
        if ratings_json != "":
            try:
                ratings = json.loads(ratings_json)
                session["ratings"] = ratings
                return render_template('ratings/spec_ratings.html')
            except JSONDecodeError:
                flash("The JSON you have input is invalid.", 'danger')
    return render_template('ratings/load_ratings.html')


@spec_ratings_blueprint.route('/save-ratings', methods=['POST'])
def save_ratings():
    ratings_dict = {}
    for wow_class, specs in wow_classes:
        ratings_dict[wow_class] = {}
        for spec in specs.split(','):
            spec_string = f'{wow_class}-{spec}'
            ratings_dict[wow_class][spec] = request.form.get(spec_string)
        ratings_dict[wow_class]['comments'] = request.form.get(f'{wow_class}-comments')
    ratings_json = json.dumps(ratings_dict, indent=4)
    session['ratings'] = ratings_dict
    return render_template('ratings/save_ratings.html', ratings_json=ratings_json)


@spec_ratings_blueprint.route('/tiermaker', methods=['GET'])
def tiermaker():
    return render_template('ratings/tiermaker.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/custom.css">
    <title>Focused Will</title>
</head>

{% set nav_bar = [
    ('index', 'home', 'Home'),
    ('spec_ratings.index', 'specs', 'Spec Ratings'),
    ('index', 'rotations', 'Rotations'),
    ('index', 'roster', 'Guild Roster'),
] -%}

{% set activate_page = active_page|default('home') -%}

<body>
<div class="content container mt-2">
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('index') }}">Focused Will</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                {% for url, id, label in nav_bar %}
                    <li class="nav-item{% if id == activate_page %} active{% endif %}">
                        <a class="nav-link" href="{{ url_for(url|e) }}">{{ label|e }}</a>
                    </li>
                {% endfor %}
                    {% if session.get('email') == None %}
                    <li class="nav-item{% if activate_page == 'login' %} active{% endif %}">
                        <a class="nav-link" data-toggle="modal" href="#incompleteFeature">Log in</a>
                    </li>
                    <li class="nav-item{% if activate_page == 'register' %} active{% endif %}">
                        <a class="nav-link" data-toggle="modal" href="#incompleteFeature">Sign up</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="modal" href="#incompleteFeature">Logout | {{ session.get('name') }}</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <div class="my-3">
    {% block content %}

    {% endblock %}
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="incompleteFeature" tabindex="-1" role="dialog" aria-labelledby="incompleteFeatureLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="incompleteFeatureLabel">Feature Incomplete</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          This feature has not yet been implemented, please try back later.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Focused Will</h1>
        <p class="lead">WoW Tools & Trackers</p>
        <hr class="my-4" />
        <p>Follow the links below or in the menu bar above to access the developed WoW tools.</p>
    </div>

    <div class="content">
        <a href="{{ url_for('spec_ratings.index') }}" class="btn btn-secondary btn-lg btn-block">Spec Ratings</a>
        <a href="#" class="btn btn-secondary btn-lg btn-block">Rotations (Incomplete)</a>
    </div>
{% endblock %}

templates/ratings/load_ratings.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Spec Ratings</h1>
        <hr class="my-4" />
        <p>Please enter the JSON string for the spec ratings below.</p>
    </div>

    <div class="content">
        <form method="post">
            <div class="form-group">
                <label for="spec-ratings">Enter your Spec Ratings JSON here:</label>
                <button type="submit" class="btn btn-primary btn-sm mb-1">Load Ratings</button>
                <textarea class="form-control" name="spec-ratings" id="spec-ratings" rows="20"></textarea>
            </div>
        </form>
    </div>
{% endblock %}

templates/ratings/save_ratings.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Spec Ratings</h1>
        <hr class="my-4" />
        <p>Copy the below JSON string and save to a txt file to be used later.</p>
    </div>

    <div class="content">
        <div class="form-group">
            <label for="spec-ratings">Spec Ratings JSON output:</label>
            <div class="d-inline-block">
                <button class="btn btn-primary btn-sm" onclick="copyToClipboard()">Copy JSON</button>
                <a href="{{ url_for('spec_ratings.index') }}" class="btn btn-secondary btn-sm">Go back</a>
            </div>
            <textarea class="form-control" rows="20" id="spec-ratings" readonly>{{ ratings_json }}</textarea>
        </div>
    </div>

    <script>
    function copyToClipboard() {
        let copyText = document.getElementById("spec-ratings");
        copyText.select();
        copyText.setSelectionRange(0, 99999);
        document.execCommand("copy");
        alert("Spec Ratings JSON copied to clipboard.")
    }
    </script>
{% endblock %}

templates/ratings/spec_ratings.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Spec Ratings</h1>
        <hr class="my-4" />
        <p>Rate specs below to be saved as JSON to a text file.</p>
    </div>

    {% set classes = [
        ('Death Knight', '#c41f3b', 'Blood,Frost,Unholy'),
        ('Demon Hunter', '#a330c9', 'Havoc,Vengence'),
        ('Druid', '#ff7d0a', 'Balance,Feral,Guardian,Restoration'),
        ('Hunter', '#a9d271', 'Beast Mastery,Marksmanship,Survival'),
        ('Mage', '#40c7eb', 'Arcane,Fire,Frost'),
        ('Monk', '#00ff96', 'Brewmaster,Mistweaver,Windwalker'),
        ('Paladin', '#f58cba', 'Holy,Protection,Retribution'),
        ('Priest', '#ffffff', 'Discipline,Holy,Shadow'),
        ('Rogue', '#fff569', 'Assassination,Outlaw,Subtlety'),
        ('Shaman', '#0070de', 'Elemental,Enhancement,Restoration'),
        ('Warlock', '#8787ed', 'Affliction,Demonology,Destruction'),
        ('Warrior', '#c79c6e', 'Arms,Fury,Protection')
    ] -%}

    {% set ratings = 5 %}

    <div class="content">
        <div class="text-center mb-3">
            <a class="btn btn-secondary btn-lg btn-block" href="{{ url_for('spec_ratings.load_ratings') }}">Load Ratings</a>
        </div>

        <form action="{{ url_for('spec_ratings.save_ratings') }}" method="post">
            <div class="form-group">
                <table class="table table-bordered table-centre">
                    <thead class="thead-dark sticky-top">
                        <tr>
                            <th scope="col" rowspan="2" style="width: 15%">Class</th>
                            <th scope="col" rowspan="2" style="width: 15%">Spec</th>
                            <th scope="col" style="width: 40%" colspan="{{ ratings }}">Rating</th>
                            <th scope="col" rowspan="2" style="width: 30%">Comments</th>
                        </tr>
                        <tr>
                            <th scope="col">Dislike</th>
                            <th scope="col">Neutral</th>
                            <th scope="col">Alright</th>
                            <th scope="col">Like</th>
                            <th scope="col">Love</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for class, class_colour, specs in classes %}
                        {% set specs = specs.split(',') %}
                        {% for i in range(specs|length) %}
                        <tr>
                        {% set class_lower = class|lower|replace(" ", "") %}
                        {% set spec_lower = specs[i]|lower|replace(" ", "") %}

                        {% if i == 0 %}
                            <td style="background-color: {{ class_colour }}" rowspan="{{ specs|length }}">{{ class }}</td>
                        {% endif %}

                            <td>{{ specs[i] }}</td>

                            {% for j in range(ratings) %}
                            <td class="py-1">
                                <div class="form-check">
                                    <input class="form-radio" type="radio" name="{{ class_lower }}-{{ spec_lower }}" value="{{ j }}" aria-label="{{ class_lower }}-{{ spec_lower }}-{{ j }}"
                                            {{ 'checked' if session['ratings'] is defined and session['ratings'][class_lower][spec_lower] == j|string }}>
                                </div>
                            </td>
                            {% endfor %}

                        {% if i == 0 %}
                            <td rowspan="{{ specs|length }}">
                                <div class="form-group mb-0">
                                    <textarea class="form-control" rows="{{ specs|length + 1 }}" name="{{ class_lower }}-comments">{{ session['ratings'][class_lower]['comments'] if session['ratings'] is defined }}</textarea>
                                </div>
                            </td>
                        {% endif %}
                        </tr>
                        {% endfor %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="form-group text-center">
                <button type="submit" class="btn btn-primary btn-lg px-5">Update</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/ratings/tiermaker.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Spec Tiermaker</h1>
        <hr class="my-4" />
        <p>Rank WoW specs. Site used is property of <a href="https://tiermaker.com">tiermaker.com</a>.</p>
        <p>Tier list created by <a href="https://twitter.com/manatee2faced?s=20">@manatee2faced</a>. Use the link above for more tier lists and create your own.</p>
    </div>

    <div class="content">
    <p class="small text-center">DISCLAIMER: This product is the intellectual property of TierMaker;
            This page is not intended for any commercial endeavors or as competition with tiermaker.com</p>
        <iframe style="width:120%; height:800px; margin-left:-10%; border:0" title="TierMaker WoW Specs"
                src="https://tiermaker.com/create/wow-specs-62777?presentationMode=true"></iframe>
    </div>
{% endblock %}

templates/simplearmory/mounts.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Spec Ratings</h1>
        <hr class="my-4" />
        <p>Rate specs below to be saved as JSON to a text file.</p>
    </div>
    <div class="content">
        <iframe style="width:100%; height:750px; margin:0; border:0" title="SimpleArmory Mounts"
                src="https://simplearmory.com/#/us/khazgoroth/dortzak/collectable/mounts"></iframe>
    </div>
{% endblock %}